services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: taskmanager_db
    restart: on-failure
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD: Password123!
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/lib/mssql

volumes:
  sqlserver_data:
