// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskManagerWebApi.Models;

#nullable disable

namespace TaskManagerWebApi.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260817123319_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TaskManagerWebApi.Models.WorkItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("WorkItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Создать диаграмму компонентов и выбрать технологии (EF Core, JWT, Swagger)",
                            Priority = "P1",
                            Status = "In Progress",
                            Title = "Разработать архитектуру бэкенда"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Реализовать регистрацию, логин, выдачу токенов и middleware для валидации",
                            Priority = "P1",
                            Status = "In Progress",
                            Title = "Настроить JWT-аутентификацию"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Написать контроллер, DTO, маппинг и репозиторий для управления рабочими элементами",
                            Priority = "P2",
                            Status = "New",
                            Title = "Создать CRUD для WorkItems"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Покрыть тестами методы GetById, Add, Update, Delete с использованием Moq",
                            Priority = "P2",
                            Status = "New",
                            Title = "Написать юнит-тесты для репозитория"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Настроить генерацию документации, добавить примеры запросов/ответов",
                            Priority = "P3",
                            Status = "In Progress",
                            Title = "Интегрировать Swagger/OpenAPI"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Реализовать Middleware для перехвата исключений и возврата кастомных JSON-ошибок",
                            Priority = "P2",
                            Status = "Pending",
                            Title = "Настроить глобальную обработку ошибок"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Добавить параметры PageNumber, PageSize, фильтр по статусу и категории",
                            Priority = "P3",
                            Status = "New",
                            Title = "Внедрить пагинацию и фильтрацию"
                        },
                        new
                        {
                            Id = 8,
                            Description = "Написать Dockerfile и docker-compose для запуска API вместе с SQL Server",
                            Priority = "P4",
                            Status = "Pending",
                            Title = "Подготовить Docker-контейнер"
                        },
                        new
                        {
                            Id = 9,
                            Description = "Добавить индексы, использовать AsNoTracking для чтения, избежать N+1",
                            Priority = "P5",
                            Status = "Closed",
                            Title = "Оптимизировать запросы к БД"
                        },
                        new
                        {
                            Id = 10,
                            Description = "Описать цели, технологии, инструкцию по запуску и примеры API-запросов",
                            Priority = "P5",
                            Status = "Closed",
                            Title = "Написать README для проекта"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
